# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e4884ddb4ad78cbb6495ac49487f8851a7ecdd61e1db14255c0fc1aeeb4f9719b3db9ca5bbea8dbe6f7d2013b8125396fe36fdab0fcbc80b15def633b9dfb13

test:
  secret_key_base: a78ca479766c5800fc3a7586b8394332b7dbbd23425b33d70de896b5e7597cef084b7b19351ada9e339de62504feeb446e92b6548437e19c1453fc43157f4752

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
